### ISSUE TITLE
No module named 'sphinx_tagtoctree'

### ISSUE THREAD

**Issue by kassbohm** [haschdl/sphinx-tagtoctree#1]
Hello,

after doing:
pip install sphinx-tagtoctree

and after entering into conf.py:

```
extensions = [
 ...
    'sphinx_tagtoctree',
    ]
```

I get the error:
`Could not import extension sphinx_tagtoctree (exception: No module named 'sphinx_tagtoctree')
`
What can I check to find out what's wrong. 

I started over today. But still having the same problem... :-/
The package is listed in "pip list" - but cannot be imported.

**Comment by haschdl** [comment]
hi @kassbohm , it's been a while since I worked on this, let me take a look!

**Comment by haschdl** [comment]
hello again @kassbohm ! I recognise that my instructions were not very clear in 2019 👎 
I made a few changes and released a new version that according to my tests seem to work now.
Could you try?
```
pip uninstall sphinx-tagtoctree
pip install sphinx-tagtoctree==0.9.4
```

**Comment by kassbohm** [comment]
> pip uninstall sphinx-tagtoctree
> pip install sphinx-tagtoctree==0.9.4
> ```

Yes, this works for me.
Thank you.

**Comment by haschdl** [comment]
You're welcome @kassbohm ! it would be nice to hear how you intended to use the extension
