### ISSUE TITLE
how to glob other rst files  if it contains both the tags swe-as-alternative-method and mp-205-23-1

### ISSUE THREAD

**Issue by rakeshcbpur** [haschdl/sphinx-tagtoctree#3]
Hi friends,

In my file, I want to glob all the .rst files that contains both the tags in same file 'swe-as-alternative-method' and 'mp-205-23-1' (only list the pages that contains both these tags)
How do we achieve using tagtoctree ? 

.. tagtoctree::
   :maxdepth: 1
   :glob:
   :tag: swe-as-alternative-method

   All Methods/[a-zA-Z]*

**Comment by haschdl** [comment]
Hi @rakeshcbpur 
Currently the extension only supports the "or" logic.  Code changes are required to support "and" . Could you tell more about your use-case and where you're using the extension? 

```rst
.. tagtoctree::
   :maxdepth: 1
   :glob:
   :caption: Pages with tag "Customer" or "Product"
   :tag: Customer, Product

```

**Comment by rakeshcbpur** [comment]
Hi @haschdl , 
Thanks for the response.
use case :  We have Method Library in confluence where each method (pages) is labeled with certain label (eg mp-205-23-1), In the end we need to group each page under 2 categories  "standard_method" or "alternative_method" . trying to build html pages now.
example :  page 1  -> label "mp-205-23-1" , "as-standard-method"
                 page 2 -> label "mp-205-23-1"    

So pages with the tag "as-standard-method" will be classified under "standard_method"
pages without the tag "as-standard-method" will be classified under "alternative-method"

In the confluence we achieve this functionality using "edit by label" macro.

So I will be looking for some way in tagtoctree like below

standard_method:

.. tagtoctree::
   :maxdepth: 1
   :glob:
   :tag: (swdetaileddesignandswconstruction or mp-205-23) and  as-standard-method

   All Methods/[a-zA-Z]* 


Alternative Methods

.. tagtoctree::
   :maxdepth: 1
   :glob:
   :tag: (swdetaileddesignandswconstruction or mp-205-23)

   All Methods/[a-zA-Z]*

**Comment by haschdl** [comment]
I understand, let me take a look into it. I think I could use [boolean.py](https://booleanpy.readthedocs.io/en/latest/index.html) to parse a more complex expression in :tag:

**Comment by haschdl** [comment]
@rakeshcbpur  I managed to get a working version, but to maintain compatibility, I created a new attribute for the expressions: `tag_expr`
So the toc tree would look like this:
```
.. tagtoctree::
   :maxdepth: 1
   :glob:
   :caption: Pages filtered with an expression
   :tag_expr: (Customer OR Product) AND Sales

   **
```

![image](https://github.com/haschdl/sphinx-tagtoctree/assets/9550197/8dd36869-c0b7-4b9c-80f1-7b5dd5b8e1ab)

Does this satisfy your requirements?

**Comment by rakeshcbpur** [comment]
@haschdl
partially yes it satisfied , not sure if "tag_expr" also supports "not" logical operator 
with our example below we try some thing like below , apologies I forgot to mention highlighted part previously , because to clearly distinguish between standard/alternative method we depends on **as-standard-method.**

standard_method:

.. tagtoctree::
:maxdepth: 1
:glob:
:tag: (swdetaileddesignandswconstruction or mp-205-23) and as-standard-method

All Methods/[a-zA-Z]*

Alternative Methods

.. tagtoctree::
:maxdepth: 1
:glob:
:tag: (swdetaileddesignandswconstruction or mp-205-23) **and (not as-standard-method)**

All Methods/[a-zA-Z]*

**Comment by rakeshcbpur** [comment]
@haschdl 
Can you please provide the update ?

**Comment by haschdl** [comment]
hello @rakeshcbpur my implementation supports "not" clauses, however it doesn't support tags containing hyphens :/
I can make a release with boolean logic , but it won't support tags with hyphens. I'm taking a look if I can fix that.

**Comment by rakeshcbpur** [comment]
@haschdl ,
regarding tags containing hyphens(-), I think currently I have tags with hyphens and they work ...but not sure how they are not working for you ..very strange

**Comment by haschdl** [comment]
> @haschdl ,
> 
> regarding tags containing hyphens(-), I think currently I have tags with hyphens and they work ...but not sure how they are not working for you ..very strange

It was not working for the Boolean expression. It's now fixed, I will publish a new version

**Comment by rakeshcbpur** [comment]
@haschdl 
Thanks for your support!!!
it seems the PR you raised is failed to create a new package ..can you please fix it

**Comment by haschdl** [comment]
@rakeshcbpur  a new alpha release is available, let me know if your tests work so I can make a new release
`pip install sphinx-tagtoctree==0.9.5.0a2`

**Comment by rakeshcbpur** [comment]
@haschdl ,
I have tested my usecases and all are working fine even NOT along with AND.
Thanks a lot once again!!! Please make new release.

**Comment by haschdl** [comment]
All right, new release available and published to pypi, I will close the issue now.
